name: patient_tracker
description: A Patient Tracker demo app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"   

dependencies:
  flutter:
    sdk: flutter
  # 这些是你代码实际用到的包
  animations: ^2.1.0
  provider: ^6.0.5
  permission_handler: ^11.3.1
  record: ^4.4.4
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.3
  just_audio: ^0.9.37
  http: ^1.2.1
  audioplayers: ^5.2.1     
  confetti: ^0.7.0
  url_launcher: ^6.2.6
  image_picker: ^1.1.1
  google_mlkit_text_recognition: ^0.12.0
  share_plus: ^7.2.2
  signature: ^5.0.0
  pdf: ^3.11.0
  printing: ^5.13.4
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  flutter_markdown: ^0.6.18
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
